name: Build ziskos

on:
  workflow_dispatch:

jobs:
  build-zisklib:
    name: Build static libziskos.a for riscv64 zkvm
    runs-on: ubuntu-22.04
    env:
      TARGET: riscv64ima-zisk-zkvm-elf
      #CARGO_TARGET_RISCV64IMA_ZISK_ZKVM_ELF_RUSTFLAGS: "-Cpasses=lower-atomic"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          #profile: minimal
          override: true

      - name: Install riscv64 toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-riscv64-unknown-elf libopenmpi-dev nlohmann-json3-dev nasm binutils-riscv64-linux-gnu
      - name: Build cargo-zisk
        run: |
          cargo build -p cargo-zisk --release
      - name: Install ZisK toolchain
        run: |
          ./target/release/cargo-zisk sdk install-toolchain
      - name: Build ziskos static library
        run: |
          git apply ./.github/workflows/cargo.toml.patch
          git apply ./.github/workflows/entrypoint-no-entrypoint.patch
          cargo +zisk build -p ziskos --release --target "${TARGET}" --features no_entrypoint
          riscv64-linux-gnu-strip "target/${TARGET}/release/libziskos.a"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ziskos-${{ env.TARGET }}
          path: target/${{ env.TARGET }}/release/libziskos.a
