name: Build ZisK binaries

on:
  push:
    branches: [pre-develop-0.16.0]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    env:
      TARGET: x86_64-unknown-linux-gnu
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          rustup toolchain install stable --profile default
          rustup default stable
          rustup target add $TARGET

      - name: Install dependencies
        run: ./tools/test-env/install_deps.sh

      - name: Build
        run: cargo build --release --target $TARGET

      - name: Pack binaries
        run: |
          mkdir -p zisk-dist/bin
          cp ./target/$TARGET/release/cargo-zisk zisk-dist/bin/
          cp ./target/$TARGET/release/ziskemu zisk-dist/bin/
          cp ./target/$TARGET/release/riscv2zisk zisk-dist/bin/
          cp ./target/$TARGET/release/zisk-coordinator zisk-dist/bin/
          cp ./target/$TARGET/release/zisk-worker zisk-dist/bin/
          cp ./ziskup/ziskup zisk-dist/bin/
          cp ./target/$TARGET/release/libziskclib.a zisk-dist/bin/

          mkdir -p zisk-dist/zisk/emulator-asm/src
          cp -r ./emulator-asm/src zisk-dist/zisk/emulator-asm
          cp -r ./lib-c/ zisk-dist/zisk
          cp ./emulator-asm/Makefile zisk-dist/zisk/emulator-asm

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cargo_zisk_linux_amd64
          path: zisk-dist
          if-no-files-found: error
